general.import  = [
    "~/.config/alacritty/arthur.toml"
]

# [shell]
# program = "/bin/zsh"

[window]
dimensions = { columns = 112, lines = 30 }
dynamic_title = false
title = "Terminal"
padding = {x = 5, y = 5}

[font]
size = 11.5

[font.normal]
# family = "UbuntuMono Nerd Font"
family = "JetBrainsMono Nerd Font"
# family = "Hack Nerd Font" 
# style = "Medium"


