general.import  = [
    "~/.config/alacritty/gruvbox.toml",
    # "~/.config/alacritty/arthur.toml",
    # "~/.config/alacritty/tokyo_night.toml"
]

[env]
term = "xterm-256color"

[window]
dimensions = { columns = 103, lines = 26 }
dynamic_title = false
title = "Terminal"
# padding = {x = 5, y = 5}

[font]
# size = 11.5
size = 12
offset = { x = 0, y = 3 }

[font.normal]
# family = "JetBrainsMono Nerd Font"
# family = "Caskaydiacove Nerd Font" 
family = "GeistMono Nerd Font" 
# family = "MesloLGM Nerd Font"
